[project]
name = "openapi2jsonschema"
version = "0.9.0"
description = "A utility to extract JSON Schema from a valid OpenAPI specification"
authors = [{ name = "Gareth Rushgrove", email = "gareth@morethanseven.net" }]
requires-python = ">=3.7,<4"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "openapi",
    "jsonschema",
]
dependencies = [
    "jsonref>=0.2.0,<1.0",
    "pyyaml>=5.1",
    "click>=8",
    "colorama>=0.4.1",
]

[project.urls]
Repository = "https://github.com/garethr/openapi2jsonschema"

[project.scripts]
openapi2jsonschema = "openapi2jsonschema.command:default"

[dependency-groups]
dev = [
    "pytest<8",
    "pytest-cov>=4.0",
    "pytest-datafiles<3",
    "pytest-black>=0.6.0",
    "pytest-mypy>=0.10.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
ignore_missing_imports = true

